### ISSUE TITLE
Faucet should respond immediately

### ISSUE THREAD

**Issue by schemar** [mosaicdao/faucet#6]
## Story
As a faucet
I want to respond to fill requests quicker
Because I don't want to block the connection for longer than necessary

## Scenario
Given that a faucet is running
When it receives a request from a client
Then it returns the txHash as soon as possible
And closes the connection without waiting for a receipt from web3

## Info
We can send the transaction with web3 and return the transaction hash to the client upon the transaction hash event from web3. We don't need to wait for the entire PromiEvent of the transaction to resolve.

Must be done in the implementations of the interface method `Faucet::fill()`. Maybe abstract it into something shared that is injected? Or maybe the `EthNode`?

**Comment by schemar** [comment]
I tried with `@types/web3` and without, however I did not manage to get the event handling working properly.

I always received the error:

```
info: Sending 100000000000000000000 EIP20 tokens to 0x3e8880f88cf9a146a9d2c5001037d6d963224b8b. {"service":"faucet"}
(node:95998) UnhandledPromiseRejectionWarning: Error: Method not found
    at WebsocketSubprovider._handleSocketMessage (/Users/martin/Projects/openst/faucet/node_modules/web3-provider-engine/subproviders/websocket.js:121:18)
    at WebSocket.onMessage (/Users/martin/Projects/openst/faucet/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:197:13)
    at Receiver.receiverOnMessage (/Users/martin/Projects/openst/faucet/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:197:13)
    at Receiver.dataMessage (/Users/martin/Projects/openst/faucet/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/Users/martin/Projects/openst/faucet/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/Users/martin/Projects/openst/faucet/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/Users/martin/Projects/openst/faucet/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/Users/martin/Projects/openst/faucet/node_modules/ws/lib/websocket.js:795:35)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
(node:95998) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)                                                                                                                                                                                               
(node:95998) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

/cc @benjaminbollen @pgev

**Comment by schemar** [comment]
I still get the same error after reverting all changes. Did some recent updates break the faucet?

**Comment by schemar** [comment]
@benjaminbollen I think this stopped working, because you shut down some of the node APIs on your server (I am connected to your server to test).
For example, an error response is `Error: The method net_version does not exist/is not available`.

**Comment by schemar** [comment]
It *does* work if I use my nodes that have all APIs turned on ...

**Comment by schemar** [comment]
@benjaminbollen we backed up your changes to `mosaic` to `mosaicbackup` and reverted mosaic. The nodes expose all APIs again on your server.

/cc @pgev

**Comment by benjaminbollen** [comment]
😱 sorry about that. Makes sense that the lower layers would query these apis to get basic info. Thanks for fixing
