### ISSUE TITLE
Faucet crashed on Socket hang up

### ISSUE THREAD

**Issue by benjaminbollen** [mosaicdao/faucet#9]
```
info: Sending 10000000000000000000 EIP20 tokens to 0xFbc7Be4B193a784194643f76C431B9f9F5896F23. {"service":"faucet"}
info: Sent 10000000000000000000 coins to 0x567aAcdF8BEf39F26BC13eF8F9A91C5B408d9960. TxHash: 0x4dcecade1bc20e6a092ea5bc13b40aa2aeb0c899d266c463e337b77aaed8946b {"service":"faucet"}
info: Sending 10000000000000000000 EIP20 tokens to 0x916e31AeACa9be6794ae1B545206abe133e02481. {"service":"faucet"}
info: Sending 10000000000000000000 coins to 0xEC16590B2ed77e2C6deBC61e6D8Aa8Fc93A8D85A. {"service":"faucet"}
info: Sent 10000000000000000000 coins to 0xEC16590B2ed77e2C6deBC61e6D8Aa8Fc93A8D85A. TxHash: 0x077abe50ac1c223ecf067f4309055e4a26f755ef097a4ba4601d9e8720746001 {"service":"faucet"}
info: Sent 10000000000000000000 EIP20 tokens to 0x916e31AeACa9be6794ae1B545206abe133e02481. TxHash: 0x2e328769af64530dbf1c6b5ce858d0bb78499ae886e72155d6a0942bc114140b {"service":"faucet"}
info: Sent 10000000000000000000 EIP20 tokens to 0xFbc7Be4B193a784194643f76C431B9f9F5896F23. TxHash: 0x28c59e2ae7e4bca8373c1a8c0ae5e9152f97e7207fee2eb750349da4c5f2b512 {"service":"faucet"}
info: Sending 10000000000000000000 coins to 0xCDA20F0395F440E536A56a4feEd9921B928E1752. {"service":"faucet"}
info: Sending 10000000000000000000 EIP20 tokens to 0x7539675BE2C6627f233837E2A5e6956F4d5D05Bf. {"service":"faucet"}
info: Sent 10000000000000000000 EIP20 tokens to 0x7539675BE2C6627f233837E2A5e6956F4d5D05Bf. TxHash: 0x83a28c2b7cad209c1bdfacf7fa9c7b82bbd8140ca91eab5c2a2ad37383ad5131 {"service":"faucet"}
info: Sent 10000000000000000000 coins to 0xCDA20F0395F440E536A56a4feEd9921B928E1752. TxHash: 0xc62a780be3c42c6647e92f3173f57ced00536c6c64e660329afed4ec80c23bf1 {"service":"faucet"}
info: Sending 10000000000000000000 coins to 0x1623CAcca91B19eA40875AB045C59e55b71DD8f4. {"service":"faucet"}
info: Sending 10000000000000000000 EIP20 tokens to 0xfb1749AE5cf6440f9a3BCcF82f0D544399a29C0d. {"service":"faucet"}
info: Sent 10000000000000000000 coins to 0x1623CAcca91B19eA40875AB045C59e55b71DD8f4. TxHash: 0x1d270cc68d4d1f46087ff802431c49271b17601824fbcb6272f5e9391f830502 {"service":"faucet"}
info: Sent 10000000000000000000 EIP20 tokens to 0xfb1749AE5cf6440f9a3BCcF82f0D544399a29C0d. TxHash: 0x3df129f0d400edc1889b02efff83716ddb5ed17fedef8033b6327ce07e8e62bd {"service":"faucet"}
info: Sending 10000000000000000000 EIP20 tokens to 0x6931c132756cD97667901fBBA24Bb609075943fE. {"service":"faucet"}
info: Sending 10000000000000000000 coins to 0xf80df4aE45AbC2F6278317aCFf1E9cBFd856ade1. {"service":"faucet"}
info: Sent 10000000000000000000 coins to 0xf80df4aE45AbC2F6278317aCFf1E9cBFd856ade1. TxHash: 0xd2af62c484a5d5744a0c5e3ed2e14f967683caa6d7f7f375e61b932dc6f9db1b {"service":"faucet"}
info: Sent 10000000000000000000 EIP20 tokens to 0x6931c132756cD97667901fBBA24Bb609075943fE. TxHash: 0xbd50c071ef842ee41e82f613aa2c927eb3280798b1afd9cf07c31adf9d657614 {"service":"faucet"}
error: uncaughtException: socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:431:23)
    at Socket.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1132:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) {"error":{"code":"ECONNRESET"},"stack":"Error: socket hang up\n    at createHangUpError (_http_client.js:330:15)\n    at Socket.socketOnEnd (_http_client.js:431:23)\n    at Socket.emit (events.js:202:15)\n    at endReadableNT (_stream_readable.js:1132:12)\n    at processTicksAndRejections (internal/process/next_tick.js:76:17)","exception":true,"date":"Tue Mar 19 2019 17:08:46 GMT+0000 (Coordinated Universal Time)","process":{"pid":31084,"uid":1000,"gid":1000,"cwd":"/home/faucet/faucet","execPath":"/usr/bin/node","version":"v11.11.0","argv":["/usr/bin/node","/home/faucet/faucet/build/faucet.js","3","200","-p","60500"],"memoryUsage":{"rss":76255232,"heapTotal":33308672,"heapUsed":27508216,"external":194915}},"os":{"loadavg":[0,0,0],"uptime":379094},"trace":[{"column":15,"file":"_http_client.js","function":"createHangUpError","line":330,"method":null,"native":false},{"column":23,"file":"_http_client.js","function":"Socket.socketOnEnd","line":431,"method":"socketOnEnd","native":false},{"column":15,"file":"events.js","function":"Socket.emit","line":202,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"endReadableNT","line":1132,"method":null,"native":false},{"column":17,"file":"internal/process/next_tick.js","function":"processTicksAndRejections","line":76,"method":null,"native":false}],"service":"faucet"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openst/faucet@0.1.0 start: `tsc && node build/faucet.js "3" "200" "-p" "60500"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openst/faucet@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/faucet/.npm/_logs/2019-03-19T17_08_49_727Z-debug.log
```

**Comment by schemar** [comment]
Socket hangups should be handled gracefully instead of crashing the faucet.

**Comment by schemar** [comment]
@benjaminbollen is there a way for me to reproduce this?

**Comment by benjaminbollen** [comment]
i took the log when the faucet was reported to be down.  I dont have a direct reproducibility action
